version: "3.7"
services:
  frontend:
    build:
      context: frontend
      target: development
    env_file:
      - ./frontend/dev.env
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/app
      - frontend-cache:/home/node/app/node_modules
  backend:
    build:
      context: backend
      target: development
    env_file:
      - ./backend/dev.env
    networks:
      - client-side
      - server-side
    ports:
      - 8000:8000
    volumes:
      - ./backend:/home/node/app
      - backend-cache:/home/node/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    env_file:
      - ./db/dev.env
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  frontend-cache: {}
  db-data: {}
