printWidth: 120
tabWidth: 2
semi: true
singleQuote: true
jsxSingleQuote: true
quoteProps: "as-needed"
trailingComma: "none"
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: "avoid"
proseWrap: "preserve"
